import { AppShell } from "@/components/layout/app-shell";
import { AlertsList } from "@/components/teacher/alerts-list";
import { HelpQueue } from "@/components/teacher/help-queue";
import { RecentActivity } from "@/components/teacher/recent-activity";
import { StatTile } from "@/components/teacher/stat-tile";
import { StepDistribution } from "@/components/teacher/step-distribution";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { requireRole } from "@/lib/auth";
import { getOrCreateGlobalConfig, getTeacherDashboardData } from "@/lib/data";

export default async function TeacherDashboardPage() {
  const user = await requireRole(["TEACHER", "ADMIN"]);
  const [{ theme }, dashboard] = await Promise.all([
    getOrCreateGlobalConfig(),
    getTeacherDashboardData(user.id, user.role === "ADMIN")
  ]);

  return (
    <AppShell
      role="teacher"
      userName={user.name}
      schoolName={theme.schoolName}
      logoUrl={theme.logoUrl}
      isAdmin={user.role === "ADMIN"}
    >
      <section className="mb-6">
        <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Teacher Dashboard</h2>
        <p className="text-sm text-slate-600 dark:text-slate-300">
          Live classroom scan for pacing, stuck points, and intervention priorities.
        </p>
      </section>

      <section className="grid gap-4 md:grid-cols-3 lg:grid-cols-6">
        <StatTile label="Active Classes" value={dashboard.totals.activeClasses} />
        <StatTile label="Active Labs" value={dashboard.totals.activeLabs} />
        <StatTile label="Students" value={dashboard.totals.students} />
        <StatTile label="In Progress" value={dashboard.statusCounts.inProgress + dashboard.statusCounts.started} />
        <StatTile label="Stuck" value={dashboard.statusCounts.stuck} hint="Needs check-in" />
        <StatTile label="Waiting" value={dashboard.statusCounts.waiting} hint="Needs teacher now" />
      </section>

      <section className="mt-5 grid gap-5 xl:grid-cols-3">
        <div className="xl:col-span-2 space-y-5">
          <Card>
            <CardTitle>Needs Teacher Now</CardTitle>
            <CardDescription>Students with unresolved help requests and waiting status.</CardDescription>
            <div className="mt-4">
              <HelpQueue requests={dashboard.needsTeacherNow} />
            </div>
          </Card>

          <StepDistribution buckets={dashboard.stepBuckets} />

          <Card>
            <CardTitle>Common Bottlenecks</CardTitle>
            <CardDescription>Where multiple students are getting stuck on the same step.</CardDescription>
            <div className="mt-3 space-y-2">
              {dashboard.bottlenecks.length === 0 ? (
                <p className="text-sm text-slate-600 dark:text-slate-300">No bottlenecks detected.</p>
              ) : (
                dashboard.bottlenecks.map((item) => (
                  <div key={`${item.labId}-${item.label}`} className="rounded-xl bg-amber-50 p-3 text-sm dark:bg-amber-900/20">
                    <p className="font-semibold text-amber-700 dark:text-amber-200">{item.labTitle}</p>
                    <p className="text-amber-700/90 dark:text-amber-100">
                      {item.label}: {item.stuckCount} students stuck ({item.count} currently on this step)
                    </p>
                  </div>
                ))
              )}
            </div>
          </Card>
        </div>

        <div className="space-y-5">
          <Card>
            <CardTitle>Class-wide Alerts</CardTitle>
            <CardDescription>Escalations generated by support rules.</CardDescription>
            <div className="mt-4">
              <AlertsList alerts={dashboard.activeAlerts} />
            </div>
          </Card>

          <RecentActivity items={dashboard.activity} />
        </div>
      </section>
    </AppShell>
  );
}
